# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=2)),
                ('carrier', models.CharField(max_length=15)),
            ],
        ),
    ]
